name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Xcode:
    strategy:
      matrix:
        xcode_version: ['latest']
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: swift -version
      - run: swift test -c release -Xswiftc -enable-testing
